name: Generar GeoJSON de tráfico

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *" # Se ejecuta cada 15 minutos
  workflow_dispatch: # Permite ejecución manual

jobs:
  generate-geojson:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9 # Ajusta según tu versión de Python

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar script para generar GeoJSON
      run: python generate_traffic_data.py

    - name: Confirmar contenido generado
      run: cat traffic_data.geojson

    - name: Subir archivo generado al repositorio
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Actualizar GeoJSON de tráfico"
        file_pattern: traffic_data.geojson
