name: Build and Fetch DGT Data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # Ejecutar cada 15 minutos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17 (using Temurin distribution)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Maven installation
        run: mvn --version  # Verifica que Maven está correctamente instalado

      - name: Build with Maven
        run: mvn clean install  # Compila el proyecto y genera el archivo GeoJSON en 'target/'

      - name: List files in target directory
        run: ls -la target/  # Verifica si el archivo GeoJSON está dentro de target/

      - name: Configure git for commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes
        run: git pull origin main  # Asegúrate de que tu rama esté actualizada

      - name: Commit GeoJSON file if updated
        run: |
          git add target/incidencias.geojson  # Añade el archivo GeoJSON
          git diff --cached --quiet || git commit -m "Update GeoJSON file"  # Solo hace commit si hay cambios
          git push origin main  # Hacer push de los cambios a la rama main

      - name: Upload GeoJSON as artifact
        uses: actions/upload-artifact@v3
        with:
          name: incidencias-geojson
          path: target/incidencias.geojson  # El archivo de
