name: Build and Fetch DGT Data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # Ejecutar cada 15 minutos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17 (using Temurin distribution)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Maven installation
        run: mvn --version  # Verifica que Maven está correctamente instalado

      - name: Build with Maven
        run: mvn clean install  # Compila el proyecto y genera el archivo GeoJSON en 'target/'

      - name: Check if the GeoJSON file exists in target/
        run: |
          echo "Checking if incidencias.geojson exists in target/"
          ls -R target/  # Listará todo el contenido dentro de target/
          if [ ! -f target/incidencias.geojson ]; then
            echo "GeoJSON file does not exist!"
            exit 1  # Esto provocará un error si el archivo no existe
          else
            echo "GeoJSON file exists."
          fi

      - name: Upload GeoJSON as artifact
        uses: actions/upload-artifact@v3
        with:
          name: incidencias-geojson
          path: target/incidencias.geojson  # Asegúrate de que el archivo GeoJSON esté disponible después de la ejecución de Maven
