name: Update Traffic Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"  # Actualiza los datos cada 5 minutos
  workflow_dispatch:

jobs:
  update-traffic-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Requirements
        run: pip install requests

      - name: Run Python Script
        run: python traffic_data.py

      - name: Confirm that the file exists
        run: |
          if [ -f "combined_traffic_data.geojson" ]; then
            echo "Archivo GeoJSON encontrado."
          else
            echo "Archivo GeoJSON NO encontrado."
            exit 1
          fi

      - name: Force Git Add
        run: git add combined_traffic_data.geojson

      - name: Commit Changes
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update traffic data" || echo "No changes to commit"

      - name: Push Changes
        run: git push
