name: Update GeoJSON

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  generate-geojson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # O la versi贸n que prefieras
          distribution: 'adoptopenjdk'  # O la distribuci贸n que prefieras (adoptopenjdk, zulu, temurin)

      - name: Build Java project
        run: mvn clean install  # O el comando que usas para compilar tu c贸digo

      - name: Run DGT Data Fetcher
        run: java -jar target/dgt-data-fetcher.jar  # O el comando adecuado para ejecutar tu c贸digo

      - name: Upload GeoJSON
        uses: actions/upload-artifact@v3
        with:
          name: geojson-output
          path: incidencias.geojson
