name: Build and Fetch DGT Data

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite la ejecución manual desde la UI de GitHub
  schedule:
    - cron: '*/15 * * * *'  # Ejecutar cada 15 minutos

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17 (using Temurin distribution)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: List files in target directory  # Paso extra para comprobar los archivos generados
        run: ls -l target/

      - name: Upload GeoJSON as artifact
        uses: actions/upload-artifact@v3
        with:
          name: incidencias-geojson
          path: target/incidencias.geojson
