jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17 (using Temurin distribution)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Maven installation
        run: mvn --version  # Verifica que Maven está correctamente instalado

      - name: Build with Maven
        run: mvn clean install  # Compila el proyecto y genera el archivo GeoJSON en la raíz

      - name: Check if the GeoJSON file exists in root directory
        run: |
          echo "Checking if incidencias.geojson exists in the root directory"
          ls -l  # Listará todo el contenido en la raíz del proyecto
          if [ ! -f incidencias.geojson ]; then
            echo "GeoJSON file does not exist!"
            exit 1  # Esto provocará un error si el archivo no existe
          else
            echo "GeoJSON file exists."
          fi

      - name: Upload GeoJSON as artifact
        uses: actions/upload-artifact@v3
        with:
          name: incidencias-geojson
          path: incidencias.geojson  # Ruta del archivo GeoJSON en la raíz
