  name: Actualizar GeoJSON

on:
  schedule:
    - cron: "0 * * * *" # Ejecutar cada hora
  workflow_dispatch: # Permitir ejecución manual

jobs:
  update-geojson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Limpiar archivos GeoJSON anteriores
        run: rm -f *.geojson # Elimina cualquier archivo GeoJSON previamente generado

      - name: Ejecutar script de actualización
        run: python traffic_data.py # Cambia "tu_script.py" por el nombre de tu archivo Python

      - name: Auto Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Actualizar GeoJSON de tráfico"
          file_pattern: "*.geojson"
          commit_options: "--allow-empty" # Forzar commit incluso si no hay cambios significativos
          branch: main
