name: Upload GeoJSON Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # Ejecutar cada 15 minutos

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check files in the root directory
        run: ls -l  # Verifica si el archivo GeoJSON está en la raíz

      - name: Upload GeoJSON as artifact
        uses: actions/upload-artifact@v3
        with:
          name: incidencias-geojson
          path: incidencias.geojson  # Asegúrate de que el archivo GeoJSON esté en la raíz
