name: Actualizar tráfico

on:
  schedule:
    - cron: '*/15 * * * *'  # Ejecutar automáticamente cada 15 minutos
  workflow_dispatch:       # Permitir ejecución manual desde la interfaz de GitHub

jobs:
  run_script:
    runs-on: ubuntu-latest  # Usar una máquina virtual con Ubuntu

    steps:
      - name: Hacer checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # O la versión que prefieras

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Instala las librerías que necesites

      - name: Ejecutar script
        run: |
          python trafico.py  # Reemplaza con el nombre de tu script

      - name: Subir los resultados a GitHub (opcional)
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Actualizar resultados de tráfico"
          git push
